import FormBet from "./Lotto/Games/FormBet";
import GameChoose from "./Lotto/Games/GameChoose";
import GameSelect from "./Lotto/Games/GameSelect";
import LottoUi from "./Lotto/LottoUi";
import TabPanel from "./Lotto/TabPanel";
let tabPanel = new TabPanel();
let formBet = new FormBet();
let gameChoose = new GameChoose(formBet);
let gameSelect = new GameSelect(formBet);
let lottoUi = new LottoUi(formBet, gameChoose, gameSelect);
lottoUi.init();
